# Firebase Configuration
# Web Key (from Browser key)
FIREBASE_WEB_API_KEY=AIzaSyCsn9WygSUkAQyHre8ws8xPmrOCf9WD3Ic

# Android Key (from Android key)
FIREBASE_ANDROID_API_KEY=AIzaSyDtEQFoUVHLXPeYuifCVYjEX6Wn3bzl0MQ

# iOS Key (from iOS key)
FIREBASE_IOS_API_KEY=AIzaSyB07RDIyFdLiXUrrWPuAczD_33iicE8s9s

FIREBASE_ANDROID_APP_ID=1:1083938880859:android:ce181dced4a4958bbfae7e
FIREBASE_IOS_APP_ID=1:1083938880859:ios:422fd71d77e352f1bfae7e
FIREBASE_WEB_APP_ID=1:1083938880859:web:9bd7166e6274a440bfae7e

# Shared Values
FIREBASE_MESSAGING_SENDER_ID=1083938880859
FIREBASE_PROJECT_ID=littlelumin-e7d26
FIREBASE_AUTH_DOMAIN=littlelumin-e7d26.firebaseapp.com
FIREBASE_DATABASE_URL=https://littlelumin-e7d26-default-rtdb.firebaseio.com
FIREBASE_STORAGE_BUCKET=littlelumin-e7d26.firebasestorage.app
FIREBASE_MEASUREMENT_ID=G-JSC6VSJTCQ

# iOS Specific
FIREBASE_IOS_CLIENT_ID=1083938880859-0t7ger4anr17h7a4l4m5f0l6kh18ithe.apps.googleusercontent.com
FIREBASE_IOS_BUNDLE_ID=com.example.littleluminq
# This builtInKotlin flag was added automatically by Flutter migrator
android.builtInKotlin=false
# This newDsl flag was added automatically by Flutter migrator
android.newDsl=false

android.useAndroidX=true
android.enableJetifier=true
org.gradle.jvmargs=-Xmx4g -XX:MaxMetaspaceSize=512m
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
# TEMPORARY - disable incremental compilation to fix cache issue
kotlin.incremental=false
org.gradle.java.home=C:/Program Files/Eclipse Adoptium/jdk-17.0.20.101-hotspot
