// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXH4ts6D5ofUpetpObR6g0EX-M6QzA70Y',
    appId: '1:1083938880859:web:9bd7166e6274a440bfae7e',
    messagingSenderId: '1083938880859',
    projectId: 'littlelumin-e7d26',
    authDomain: 'littlelumin-e7d26.firebaseapp.com',
    databaseURL: 'https://littlelumin-e7d26-default-rtdb.firebaseio.com',
    storageBucket: 'littlelumin-e7d26.firebasestorage.app',
    measurementId: 'G-JSC6VSJTCQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWGAsKnIPnWm6Cr_qvZdgYR1zavVqa20s',
    appId: '1:1083938880859:android:ce181dced4a4958bbfae7e',
    messagingSenderId: '1083938880859',
    projectId: 'littlelumin-e7d26',
    databaseURL: 'https://littlelumin-e7d26-default-rtdb.firebaseio.com',
    storageBucket: 'littlelumin-e7d26.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzxTJAEcMlPGDaLdwIEdOSr8DZkXqfLYk',
    appId: '1:1083938880859:ios:422fd71d77e352f1bfae7e',
    messagingSenderId: '1083938880859',
    projectId: 'littlelumin-e7d26',
    databaseURL: 'https://littlelumin-e7d26-default-rtdb.firebaseio.com',
    storageBucket: 'littlelumin-e7d26.firebasestorage.app',
    iosClientId: '1083938880859-0t7ger4anr17h7a4l4m5f0l6kh18ithe.apps.googleusercontent.com',
    iosBundleId: 'com.example.littlelumin',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDzxTJAEcMlPGDaLdwIEdOSr8DZkXqfLYk',
    appId: '1:1083938880859:ios:422fd71d77e352f1bfae7e',
    messagingSenderId: '1083938880859',
    projectId: 'littlelumin-e7d26',
    databaseURL: 'https://littlelumin-e7d26-default-rtdb.firebaseio.com',
    storageBucket: 'littlelumin-e7d26.firebasestorage.app',
    iosClientId: '1083938880859-0t7ger4anr17h7a4l4m5f0l6kh18ithe.apps.googleusercontent.com',
    iosBundleId: 'com.example.littlelumin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDXH4ts6D5ofUpetpObR6g0EX-M6QzA70Y',
    appId: '1:1083938880859:web:ec5fd5dbe417d2d3bfae7e',
    messagingSenderId: '1083938880859',
    projectId: 'littlelumin-e7d26',
    authDomain: 'littlelumin-e7d26.firebaseapp.com',
    databaseURL: 'https://littlelumin-e7d26-default-rtdb.firebaseio.com',
    storageBucket: 'littlelumin-e7d26.firebasestorage.app',
    measurementId: 'G-NR22PDPVZ1',
  );
}
