// lib/firebase_options.dart
// File generated by FlutterFire CLI with .env support for secure key storage
// ignore_for_file: type=lint

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:flutter_dotenv/flutter_dotenv.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    // Load environment variables
    final apiKey = dotenv.env['FIREBASE_API_KEY']!;
    final appId = dotenv.env['FIREBASE_APP_ID']!;
    final messagingSenderId = dotenv.env['FIREBASE_MESSAGING_SENDER_ID']!;
    final projectId = dotenv.env['FIREBASE_PROJECT_ID']!;
    final authDomain = dotenv.env['FIREBASE_AUTH_DOMAIN']!;
    final databaseURL = dotenv.env['FIREBASE_DATABASE_URL']!;
    final storageBucket = dotenv.env['FIREBASE_STORAGE_BUCKET']!;
    final measurementId = dotenv.env['FIREBASE_MEASUREMENT_ID']!;

    if (kIsWeb) {
      return FirebaseOptions(
        apiKey: apiKey,
        appId: appId,
        messagingSenderId: messagingSenderId,
        projectId: projectId,
        authDomain: authDomain,
        databaseURL: databaseURL,
        storageBucket: storageBucket,
        measurementId: measurementId,
      );
    }

    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return FirebaseOptions(
          apiKey: apiKey,
          appId: appId,
          messagingSenderId: messagingSenderId,
          projectId: projectId,
          databaseURL: databaseURL,
          storageBucket: storageBucket,
        );
      case TargetPlatform.iOS:
        return FirebaseOptions(
          apiKey: apiKey,
          appId: appId,
          messagingSenderId: messagingSenderId,
          projectId: projectId,
          databaseURL: databaseURL,
          storageBucket: storageBucket,
          iosClientId: dotenv.env['FIREBASE_IOS_CLIENT_ID'],
          iosBundleId: dotenv.env['FIREBASE_IOS_BUNDLE_ID'],
        );
      case TargetPlatform.macOS:
        return FirebaseOptions(
          apiKey: apiKey,
          appId: appId,
          messagingSenderId: messagingSenderId,
          projectId: projectId,
          databaseURL: databaseURL,
          storageBucket: storageBucket,
          iosClientId: dotenv.env['FIREBASE_IOS_CLIENT_ID'],
          iosBundleId: dotenv.env['FIREBASE_IOS_BUNDLE_ID'],
        );
      case TargetPlatform.windows:
        return FirebaseOptions(
          apiKey: apiKey,
          appId: appId,
          messagingSenderId: messagingSenderId,
          projectId: projectId,
          authDomain: authDomain,
          databaseURL: databaseURL,
          storageBucket: storageBucket,
          measurementId: measurementId,
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }
}